#pragma once
#include <vector>
#include <iostream>
#include <filesystem>
#include <typeinfo>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "iostream"
#include "fstream"
#include <Shaders/shader.h>
#include <StbImage/stb_image.h>
#include <glm/glm.hpp>
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/type_ptr.hpp>
#include <Camera/camera.h>