#pragma once
#include <iostream>
#include <filesystem>
#include <typeinfo>
#include <glad/glad.h>
#include <GLFW/glfw3.h>
#include "iostream"
#include "fstream"
#include <Shaders/shader.h>
#include <StbImage/stb_image.h>